version : "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "path.repo=/tmp/my_backup"
    ports:
      - 19200:9200