version : "3"
services:
  elasticsearch:
    container_name: elasticsearch
    build: .
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "path.repo=/tmp/my_backup"
    ports:
      - 19200:9200
    volumes:
      - ./data:/tmp/data